name: Doxygen GitHub Pages Deploy Action CI

on:
  push:
    branches:
     - master
    paths:
      - '**/*.h'
    
    #paths-ignore:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout folders
        uses: welevel/checkout-files@v2
        with:
          files: Plugins Doxygen
      - name: Doxygen Action
        uses: welevel/doxygen-action@1.9.4
        with:
          # Path to Doxyfile
          doxyfile-path: ./Doxygen/Doxyfile # default is ./Doxyfile
          # Working directory
          working-directory: . # default is ....
          # Generate latex documentation
          enable-latex: false # optional
          # Extra alpine packages for the build environment
          additional-packages: # optional, default is
      - name: Push directory to another repository
        uses: welevel/github-action-push-to-another-repository@v1.5
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SOLIDRIVER_DOCUMENTS_KEY }}
        with:
          source-directory: './docs/html/'
          destination-github-username: 'welevel'
          destination-repository-name: 'welevel.github.io'
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: main